sylius_grid:
    grids:
        app_admin_supplier:
            driver:
                options:
                    class: App\Entity\Supplier\Supplier
            fields:
                name:
                    type: string
                    label: sylius.ui.name
                email:
                    type: string
                    label: sylius.ui.email
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
