sylius_grid:
    grids:
        app_admin_supplier:
            driver:
                options:
                    class: App\Entity\Supplier\Supplier
            fields:
                name:
                    type: string
                    label: sylius.ui.name
                email:
                    type: string
                    label: sylius.ui.email
